name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or whatever version you use

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone gh-pages branch in temp folder
          git clone --branch=gh-pages https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} gh-pages-temp

          # Copy build files to gh-pages-temp (overwriting matching files)
          cp -r dist/* gh-pages-temp/
          
          # ✅ Copy DB folder too
          rm -rf gh-pages-temp/DB  
          cp -r src/DB gh-pages-temp/DB

          # Commit and push changes
          cd gh-pages-temp
          git add .
          git commit -m "Deploy from development branch: ${{ github.sha }}" || echo "No changes to commit"
          git push

